-- sqlplus로 실행할 것 (eclipse에서 실행시 에러 발생)

DROP TABLE CS_TABLE;

CREATE TABLE CS_TABLE (
	NO	NUMBER(4) PRIMARY KEY,
	ITEM	VARCHAR2(10),
	DSC	VARCHAR2(30)
);

CREATE OR REPLACE PROCEDURE CS_PROC 
(VNO CS_TABLE.NO%TYPE, VITEM CS_TABLE.ITEM%TYPE, VDSC CS_TABLE.DSC%TYPE)
IS
BEGIN
	INSERT INTO CS_TABLE(NO, ITEM, DSC) VALUES (VNO, VITEM, VDSC);
END CS_PROC;
